# Generated by Django 4.2.21 on 2025-06-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
