# Generated by Django 4.2.21 on 2025-06-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_firstname_member_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='base',
            field=models.CharField(default='Canyons', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='ski_area',
            field=models.CharField(default='Park City Mountain Resort', max_length=100),
        ),
    ]
