# Generated by Django 4.2.21 on 2025-06-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_base_member_ski_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='epic_PassNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='physical_PassNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
