# Generated by Django 4.2.21 on 2025-06-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_epic_passnumber_member_physical_passnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='epic_PassNumber',
            field=models.BigIntegerField(null=True, verbose_name='Passnumber list on the Epic Mix app.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='physical_PassNumber',
            field=models.BigIntegerField(null=True, verbose_name='Passnumber listed on your printed Epic pass.'),
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.resort')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.base'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ski_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.resort'),
        ),
    ]
