# Generated by Django 4.2.21 on 2025-06-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_resort_alter_member_epic_passnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='base',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ski_area',
        ),
    ]
