# Generated by Django 4.2.21 on 2025-06-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_member_base_remove_member_ski_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ski_area',
            field=models.CharField(default='Park City Mountain Resort', max_length=100),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
    ]
