# Generated by Django 4.2.21 on 2025-06-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_ski_area_delete_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='epic_PassNumber',
        ),
        migrations.RemoveField(
            model_name='member',
            name='physical_PassNumber',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ski_area',
        ),
    ]
