# Generated by Django 4.2.21 on 2025-06-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_member_epic_passnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='epic_PassNumber',
            field=models.BigIntegerField(null=True, verbose_name='Passnumber list on the Epic Mix app.'),
        ),
        migrations.AddField(
            model_name='member',
            name='physical_PassNumber',
            field=models.BigIntegerField(null=True, verbose_name='Passnumber listed on your printed Epic pass.'),
        ),
    ]
