# Generated by Django 4.2.21 on 2025-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_epic_passnumber_member_physical_passnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='area',
            new_name='location',
        ),
        migrations.AddField(
            model_name='resort',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
