# Generated by Django 4.2.21 on 2025-06-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_rename_area_resort_location_resort_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ski_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Resort',
        ),
    ]
