# Generated by Django 4.2.21 on 2025-06-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_ski_area_delete_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ski_area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
