# Generated by Django 4.2.21 on 2025-06-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_ski_area_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('create_exchange', 'Can exhange available schedule'), ('delete_exchange', 'Can remove exchanged schedule')]},
        ),
    ]
